### ISSUE TITLE
Paginated eleventyComputed eleventyNavigation

### ISSUE THREAD

**Issue by enly1** [11ty/eleventy-navigation#24]
I'm trying to get a paginated global dataset to add items for use with the navigation plugin, but only the first item in the paginated set gets added.

The following is the navigation dump once 10 items have been paginated:

**Snippet from `layouts/main.njk`:**
```
    {% set navPages = collections.all | eleventyNavigation %}
    {{ navPages | dump }} 
```
**Generates:**
```
[{"key":"Jackie Chan","title":"Jackie Chan","url":"/influencer/jackie-chan/","pluginType":"eleventy-navigation","children":[{"key":"JC-SKU1","title":"JC-SKU1","parent":"Jackie Chan","url":"/influencer/jackie-chan/jc-sku1/","pluginType":"eleventy-navigation","parentKey":"Jackie Chan","children":[]}]}]
```

Only 1 item appears for each of the paginated sets.  In this case influencers and influencer products paginated sets.

**Example from the influencer products frontmatter:**
```
---
layout: layouts/main.njk
pagination:
    data: influencer_products
    size: 1
    alias: product
permalink: /influencer/{{product.channel | slug }}/{{ product.id | slug}}/
eleventyComputed:
    eleventyNavigation:
        key: "{{product.id}}"
        title: "{{product.id}}"
        parent: "{{product.channel}}"
    title: "Product: {{product.channel}}"
---
```

I have also tried doing this without using frontmatter and injecting eleventyComputed output from js and that results in the same output.

Can navigation be used in this way with pagination ?

**Comment by bckmnn** [comment]
I had a similar problem, and after some digging found [this in the docs](https://www.11ty.dev/docs/pagination/#add-all-pagination-pages-to-collections). Modifying your frontmatter like this should help:
```
pagination:
    data: influencer_products
    size: 1
    alias: product
    addAllPagesToCollections: true
```
