### ISSUE TITLE
support reuse of keys from front-matter

### ISSUE THREAD

**Issue by Dexus** [11ty/eleventy-navigation#40]
I have some keys, and I would love to have the possibility to reuse them like:

```yaml
---
title: "Projekte"
translationKey: "page-projects"
eleventyNavigation:
  key: "{{ translationKey }}"
  title: "{{ title }}"
---
```
