### ISSUE TITLE
Define all items in global data file

### ISSUE THREAD

**Issue by silveltman** [11ty/eleventy-navigation#42]
Define all items in global data file. Like so:

__data/navigation.yaml_
```
items:
  - key: home
    title: Home
    url: /
    children:
      - key: Second
        title: Second
        url: /
        children:
  - key: contact
    title: Contact
    url: /contact
```
