### ISSUE TITLE
duplicated mapping key error for title

### ISSUE THREAD

**Issue by TaylanTatli** [11ty/eleventy-navigation#5]
Hi! Trying to use this plugin to organize my notes. Since i can't give all my notes a key, i just add parent but it gives "undefined" as title. in my frontmatter there is already title and when i set a title for navigation it gives "duplicated mapping key error".

Here is an example;

Parent:
```
---
layout: docs
eleventyNavigation:
  key: Tarih
---
``` 

Child:
```
---
title: Lorem ipsum
layout: docs
date: 2019-10-03T19:36:17.272Z
weight: 5
eleventyNavigation:
  parent: Tarih
---
```

When i do this:
```
---
title: Lorem ipsum
layout: docs
date: 2019-10-03T19:36:17.272Z
weight: 5
eleventyNavigation:
  parent: Tarih
  title: Lorem ipsum
---
```

It gives error but i don't even want to use title since there is already one for all my notes. What should i do?
